# Default values for social-network.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx-ingress:
  fullnameOverride: "nginx-ingress"

inventory:
  fullnameOverride: "inventory-service"

orders:
  fullnameOverride: "order-service"